### PR TITLE
Reduce number of calls to host app when computing badge counters

### LINKED ISSUE #135: Google Drive spreadsheet triggers high CPU usage in Firefox (a infinite loop with browserpass?)
### General information

-   Operating system + version: Windows 10 1809
-   Browser + version: Firefox 66.0.3 (64-bits)
-   Information about the host app:
    -   How did you install it?
        Downloaded a pre-built binary (`browserpass-windows64-3.0.6.zip`)
-   Information about the browser extension:
    -   How did you install it?
        Webstore
    -   Browserpass extension version as reported by your browser:
        3.1.0

### Exact steps to reproduce the problem

1. Open any Google Drive Spreadsheet (https://docs.google.com/spreadsheets/) via drive.google.com

2. Firefox CPU and memory usage goes unusual high

3. `browserpass-windows64.exe` is spawned at least 50x

### What should happen?
The extension should list the available logins.

### What happened instead?
* Before opening the spreadsheet (or opening with browserpass extension disabled) Before opening the spreadsheet (or opening with browserpass extension disabled)
* Opening spreadsheet via Google Drive Opening spreadsheet via Google Drive
* Firefox main proccess high CPU and memory usage, plus the spawning of browserpass Firefox main proccess high CPU and memory usage, plus the spawning of browserpass
* 5min later, the proccesses still running and `firefox.exe` still with high CPU consume 5min later, the proccesses still running and firefox.exe still with high CPU consume
* At least 50 child proccesses At least 50 child proccesses
* The badge counts the number of logins available for the domain (google.com) but don't load them The badge counts the number of logins available for the domain (google.com) but don't load them

I've noticed the high CPU usage and breakdowns after using the new browserpass. Just today I reproduce this issue by opening spreadsheets and monitoring via Process Explorer.

### LINKED ISSUE #138: "Loading available logins..." get's stuck.
### General information

-   Operating system + version: Windows Server 2019 Standard Edition, Version 1809
-   Browser + version: Firefox Quantum 66.0.3 (64-Bit)
-   Information about the host app:
    -   Host app installed via MSI (3.0.6)
-   Information about the browser extension:
    -   Installed via addons.mozilla.org
    -   Browserpass extension version as reported by your browser: 3.1.1
- Using gpg/smartcard for pw decryption

### The Issue
Reproduce:
1. Browse for a while (exact cause unknown)

When using the key combination ctrl+shift+L the popup appears and only shows "Loading available logins..." forever. It seems stuck and will happen from then on on every page. Restarting firefox solves the issue for a while.  
I tried a few things to reproduce it, but it seems pretty random so far. I'll update if new info comes up.

### PR DESCRIPTION
**Pull request by maximbaz**
@erayd what do you think of such naive caching approach? I didn't want to deal with tab management (monitoring when user navigates between tabs, when URL in the tab is changed, when tab is opened or closed, etc.), so instead on _every_ tab event a badge is refreshed. However now the badge counter is cached per hostname, so in majority of cases the code will not attempt to talk to host app.

I recommend reviewing with `?w=1`

Fixes #135 
Fixes #138

### CODE REVIEW

File: src/background.js [hunk 1]
```diff
@@ -102,39 +106,53 @@ chrome.runtime.onInstalled.addListener(onExtensionInstalled);
...
+async function updateMatchingPasswordsCount(tabId, forceRefresh = false) {
     try {
-        const settings = await getFullSettings();
-        var response = await hostAction(settings, "list");
-        if (response.status != "ok") {
-            throw new Error(JSON.stringify(response));
+        if (forceRefresh || Date.now() > badgeCache.expires) {
+            badgeCache = {
+                files: null,
+                settings: null,
```
Comment (erayd) [inline src/background.js]: Perhaps put `await getFullSettings()` here? Seems odd to define this null, and then immediately set it.

File: src/background.js [hunk 2]
```diff
@@ -102,39 +106,53 @@ chrome.runtime.onInstalled.addListener(onExtensionInstalled);
...
  */
-async function updateMatchingPasswordsCount(tabId) {
+async function updateMatchingPasswordsCount(tabId, forceRefresh = false) {
     try {
-        const settings = await getFullSettings();
-        var response = await hostAction(settings, "list");
-        if (response.status != "ok") {
-            throw new Error(JSON.stringify(response));
+        if (forceRefresh || Date.now() > badgeCache.expires) {
+            badgeCache = {
```
Comment (erayd) [inline src/background.js]: We shouldn't overwrite the cache here. Build a new cache object, and then overwrite once it's complete. That way we avoid any race conditions where something might go to look at the cache, and find it in the middle of a refresh.

File: src/background.js [hunk 3]
```diff
@@ -102,39 +106,53 @@ chrome.runtime.onInstalled.addListener(onExtensionInstalled);
...
+
+            var response = await hostAction(badgeCache.settings, "list");
+            if (response.status != "ok") {
+                throw new Error(JSON.stringify(response));
+            }
+
+            badgeCache.files = response.data.files;
+        }
+
+        if (badgeCache.files === null) {
```
Comment (erayd) [inline src/background.js]: As above. If we eliminate the race condition, then there's no need for this check.

File: src/background.js [hunk 4]
```diff
@@ -102,39 +106,53 @@ chrome.runtime.onInstalled.addListener(onExtensionInstalled);
...
             const tab = await chrome.tabs.get(tabId);
-            settings.host = new URL(tab.url).hostname;
+            badgeCache.settings.host = new URL(tab.url).hostname;
         } catch (e) {
             throw new Error(`Unable to determine domain of the tab with id ${tabId}`);
         }
 
-        const files = helpers.ignoreFiles(response.data.files, settings);
-        const logins = helpers.prepareLogins(files, settings);
+        // Compule badge counter
```
Comment (erayd) [inline src/background.js]: s/Compule/Compile/
